### ISSUE TITLE
Cannot enter filepath 

### ISSUE THREAD

**Issue by mborn319** [yuanchuan/markdown-preview#10]
Say I am in `/var/www`, and I want to preview `/var/www/Boombox/README.md`.

I run 
````bash
$ markdown-preview Boombox/README.md
````
There is no error, but `http://localhost:3333/README.md` shows a blank page. 

Is there any good way to get this to work?

Also, interestingly, if I cd to `/usr/local/lib/node_modules/markdown-preview`, and attempt to preview my README with an absolute filename...

````bash
$ cd /usr/local/lib/node_modules/markdown-preview
$ markdown-preview /var/www/Boombox/README.md 
````
now `http://localhost:3333/README.md` shows the preview for markdown-preview/README.md! Basically, the path is stripped from the filename argument. This seems like a separate issue, but I'm not sure.

**Comment by yuanchuan** [comment]
Probably the `path.resolve` returned the wrong path.  Could you provide your OS name and the Node.js version that is running?

**Comment by yuanchuan** [comment]
As you run `markdown-preview somefile.md`, it will open the browser and navigate to it automatically.  seeing your description in #11, I guess it failed to open the browser?

**Comment by yuanchuan** [comment]
Close for now. Please let me know if there're other problems
