### ISSUE TITLE
Add a stackedit flavoured preview

### ISSUE THREAD

**Issue by doronbehar** [yuanchuan/markdown-preview#17]
Among all the markdown parsers and previewers I've encountered, this one is the best.
But I was wondering, in [https://stackedit.io](https://stackedit.io) ([source code](https://github.com/benweet/stackedit)), @benweet implements at least one feature most markdwon flavours don't, it's "LaTeX mathematical expressions using MathJax". I find this and some other features extremely useful but I wish I could use them with my own text-editor. I think that adding `stackedit` as a parser for `markdown-preview` will be great. Unfortunately I don't know enough JavaScript to make a PR, yet I couldn't not resist sharing the idea.

I'll be glad to hear your thoughts.

**Comment by yuanchuan** [comment]
Glad you find this tool useful. I'll try to add those features.

**Comment by yuanchuan** [comment]
I've just added basic Mathjax support.  You can try it out by upgrading to the latest version:

```
$ npm upgrade -g markdown-preview
```
And wrap math expressions around with `<p>` if anything's going wrong.

```
<p>
  \begin{align}
   \dot{x} & = \sigma(y-x) \\
   \dot{y} & = \rho x - y - xz \\
   \dot{z} & = -\beta z + xy
  \end{align}
</p>
```

**Comment by doronbehar** [comment]
It's Great! exactly like I expected.
