### ISSUE TITLE
Watch for file changes and reload automatically

### ISSUE THREAD

**Issue by sdkks** [yuanchuan/markdown-preview#20]
First of all thanks for making this awesome tool.

Could it be possible to add a `--watch` option for this CLI tool, so we can just refresh browser and see the changes?

**Comment by yuanchuan** [comment]
The watch mechanism is enabled by default and refreshes the browser automatically. 
Somehow the watch did not work?

**Comment by sdkks** [comment]
My bad, it's working actually.

**Comment by yuanchuan** [comment]
😃 That's ok!   
Pull requests are always welcome!
