### ISSUE TITLE
Github Flavored Markdown

### ISSUE THREAD

**Issue by codeHatcher** [yuanchuan/markdown-preview#4]
Adding Github Flavored Markdown would be a nice touch. Right now I am using your previewer with vim for simple markup previewing. It makes it nice and lightweight for my needs vs the much more complex solutions. Just a thought.

**Comment by yuanchuan** [comment]
Finally, I managed to make it looks nicer.

**Comment by addisonamiri** [comment]
https://github.com/chjj/marked could do the parsing for you. It seems like the best local gfm parser.

**Comment by yuanchuan** [comment]
Hi @addisonamiri  @codeHatcher,  thanks for your suggestions. I'll leave it as it is right now since I've just realized there're a lot of markdown previewer out there and are much better mine, unless someone still has interested in this one.

**Comment by addisonamiri** [comment]
<sub><sub>but I like yours the best</sub></sub>

**Comment by yuanchuan** [comment]
you're so nice :)

**Comment by gazliddon** [comment]
Yeah I like this one best too :D Added a pull request with marked parsing included. Seems to work fine.

**Comment by yuanchuan** [comment]
Thanks @gazliddon ,  I've merged in and published to npm :)
