### ISSUE TITLE
'yuanchuan' is not in the npm registry

### ISSUE THREAD

**Issue by muralikodali** [yuanchuan/markdown-preview#8]
sudo npm install -g markdown-preview giving following error

npm ERR! 404 'yuanchuan' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it

**Comment by yuanchuan** [comment]
Oh! 
Would you please tell me the npm version?

**Comment by muralikodali** [comment]
My npm version is 1.3.10

Output from terminal for the command :sudo npm install -g
markdown-preview is below

npm http GET https://registry.npmjs.org/markdown-preview
npm http 304 https://registry.npmjs.org/markdown-preview
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/marked/0.3.5
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/node-watch
npm http GET https://registry.npmjs.org/open
npm http GET https://registry.npmjs.org/yuanchuan/redis-commands/0.0.4
npm http GET https://registry.npmjs.org/showdown
npm http 304 https://registry.npmjs.org/node-watch
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/marked/0.3.5
npm http 304 https://registry.npmjs.org/open
npm http 304 https://registry.npmjs.org/showdown
npm http 404 https://registry.npmjs.org/yuanchuan/redis-commands/0.0.4
npm ERR! 404 'yuanchuan' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "markdown-preview"
npm ERR! cwd /home/murali
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/murali/npm-debug.log
npm ERR! not ok code 0

On Wed, Dec 23, 2015 at 07:42:05AM -0800, Yuan Chuan wrote:
> Oh!
> Would you please tell me the npm version?
> 
> ?
> Reply to this email directly or [1]view it on GitHub.*
> 
> 
> References:
> 
> [1] https://github.com/yuanchuan/markdown-preview/issues/8#issuecomment-166926453

-- 
Regards,
Murali Kodali

**Comment by yuanchuan** [comment]
The package  "https://registry.npmjs.org/yuanchuan/redis-commands/0.0.4" is actually a scoped package, which npm v1.3.10 failed to recognize.

I've removed the `redis-commands` package and published a new version,  please check if it works now :D

**Comment by muralikodali** [comment]
On Wed, Dec 23, 2015 at 09:06:41PM -0800, Yuan Chuan wrote:
> The package "[1]https://registry.npmjs.org/yuanchuan/redis-commands/0.0.4" is
> actually a scoped package, which npm v1.3.10 failed to recognize.
> 
> I've removed the redis-commands package and published a new version, please
> check if it works now :D
> 
> ?
> Reply to this email directly or [2]view it on GitHub.*
> 
> 
> References:
> 
> [1] https://registry.npmjs.org/yuanchuan/redis-commands/0.0.4
> [2] https://github.com/yuanchuan/markdown-preview/issues/8#issuecomment-167043212

Problem solved

Thank you

-- 
Regards,
Murali Kodali
