### ISSUE TITLE
Markdown-preview `-h` option does not output help info

### ISSUE THREAD

**Issue by mborn319** [yuanchuan/markdown-preview#9]
`$ markdown-preview -h`
returns `error: option `-h, --highlight <highlight>' argument missing`.

This is because the `-h` option is mapped to the `--highlight` argument, instead of the `--help` argument like the docs say.

See the `--help` output:
````bash
$ markdown-preview --help
  Usage: markdown-preview [options] <filename>
  Options:
    -h, --help                   output usage information
    -V, --version                output the version number
    -m, --marked                 use marked to parse markdown
    -p, --port <port>            server port (defaults to 3333)
    -c, --css <name>             use customize css file for styling
    -h, --highlight <highlight>  set highlight style
`````

Let me know if you need more info.

**Comment by yuanchuan** [comment]
Oops,  it seems by removing the `-h` for the  `--highlight` option would be a quick fix.

**Comment by yuanchuan** [comment]
Any better suggestion on this?

**Comment by mborn319** [comment]
Could you change the `-h` to a `-i`, just to leave a short option?
